/**
 * @file Contains the interface and an array of objects for country data.
 * @exports CountryCode - The interface for a country object.
 * @exports countryCodes - An array of all countries with their respective codes.
 */

/**
 * Interface representing a country with its various codes.
 */
export interface ICountryCode {
    name: string;
    alpha2: string; // ISO 3166-1 alpha-2
    alpha3: string; // ISO 3166-1 alpha-3
    numeric: string; // ISO 3166-1 numeric-3
    code: string; // International calling code
}

/**
 * An array of country objects, conforming to the ICountryCode interface.
 */
export const COUNTRY_CODE_LIST: ICountryCode[] = [
    { name: 'Afghanistan', alpha2: 'AF', alpha3: 'AFG', numeric: '004', code: '+93' },
    { name: 'Åland Islands', alpha2: 'AX', alpha3: 'ALA', numeric: '248', code: '+358' },
    { name: 'Albania', alpha2: 'AL', alpha3: 'ALB', numeric: '008', code: '+355' },
    { name: 'Algeria', alpha2: 'DZ', alpha3: 'DZA', numeric: '012', code: '+213' },
    { name: 'American Samoa', alpha2: 'AS', alpha3: 'ASM', numeric: '016', code: '+1-684' },
    { name: 'Andorra', alpha2: 'AD', alpha3: 'AND', numeric: '020', code: '+376' },
    { name: 'Angola', alpha2: 'AO', alpha3: 'AGO', numeric: '024', code: '+244' },
    { name: 'Anguilla', alpha2: 'AI', alpha3: 'AIA', numeric: '660', code: '+1-264' },
    { name: 'Antarctica', alpha2: 'AQ', alpha3: 'ATA', numeric: '010', code: '+672' },
    { name: 'Antigua and Barbuda', alpha2: 'AG', alpha3: 'ATG', numeric: '028', code: '+1-268' },
    { name: 'Argentina', alpha2: 'AR', alpha3: 'ARG', numeric: '032', code: '+54' },
    { name: 'Armenia', alpha2: 'AM', alpha3: 'ARM', numeric: '051', code: '+374' },
    { name: 'Aruba', alpha2: 'AW', alpha3: 'ABW', numeric: '533', code: '+297' },
    { name: 'Australia', alpha2: 'AU', alpha3: 'AUS', numeric: '036', code: '+61' },
    { name: 'Austria', alpha2: 'AT', alpha3: 'AUT', numeric: '040', code: '+43' },
    { name: 'Azerbaijan', alpha2: 'AZ', alpha3: 'AZE', numeric: '031', code: '+994' },
    { name: 'Bahamas', alpha2: 'BS', alpha3: 'BHS', numeric: '044', code: '+1-242' },
    { name: 'Bahrain', alpha2: 'BH', alpha3: 'BHR', numeric: '048', code: '+973' },
    { name: 'Bangladesh', alpha2: 'BD', alpha3: 'BGD', numeric: '050', code: '+880' },
    { name: 'Barbados', alpha2: 'BB', alpha3: 'BRB', numeric: '052', code: '+1-246' },
    { name: 'Belarus', alpha2: 'BY', alpha3: 'BLR', numeric: '112', code: '+375' },
    { name: 'Belgium', alpha2: 'BE', alpha3: 'BEL', numeric: '056', code: '+32' },
    { name: 'Belize', alpha2: 'BZ', alpha3: 'BLZ', numeric: '084', code: '+501' },
    { name: 'Benin', alpha2: 'BJ', alpha3: 'BEN', numeric: '204', code: '+229' },
    { name: 'Bermuda', alpha2: 'BM', alpha3: 'BMU', numeric: '060', code: '+1-441' },
    { name: 'Bhutan', alpha2: 'BT', alpha3: 'BTN', numeric: '064', code: '+975' },
    { name: 'Bolivia (Plurinational State of)', alpha2: 'BO', alpha3: 'BOL', numeric: '068', code: '+591' },
    { name: 'Bonaire, Sint Eustatius and Saba', alpha2: 'BQ', alpha3: 'BES', numeric: '535', code: '+599' },
    { name: 'Bosnia and Herzegovina', alpha2: 'BA', alpha3: 'BIH', numeric: '070', code: '+387' },
    { name: 'Botswana', alpha2: 'BW', alpha3: 'BWA', numeric: '072', code: '+267' },
    { name: 'Bouvet Island', alpha2: 'BV', alpha3: 'BVT', numeric: '074', code: '+47' },
    { name: 'Brazil', alpha2: 'BR', alpha3: 'BRA', numeric: '076', code: '+55' },
    { name: 'British Indian Ocean Territory', alpha2: 'IO', alpha3: 'IOT', numeric: '086', code: '+246' },
    { name: 'Brunei Darussalam', alpha2: 'BN', alpha3: 'BRN', numeric: '096', code: '+673' },
    { name: 'Bulgaria', alpha2: 'BG', alpha3: 'BGR', numeric: '100', code: '+359' },
    { name: 'Burkina Faso', alpha2: 'BF', alpha3: 'BFA', numeric: '854', code: '+226' },
    { name: 'Burundi', alpha2: 'BI', alpha3: 'BDI', numeric: '108', code: '+257' },
    { name: 'Cabo Verde', alpha2: 'CV', alpha3: 'CPV', numeric: '132', code: '+238' },
    { name: 'Cambodia', alpha2: 'KH', alpha3: 'KHM', numeric: '116', code: '+855' },
    { name: 'Cameroon', alpha2: 'CM', alpha3: 'CMR', numeric: '120', code: '+237' },
    { name: 'Canada', alpha2: 'CA', alpha3: 'CAN', numeric: '124', code: '+1' },
    { name: 'Cayman Islands', alpha2: 'KY', alpha3: 'CYM', numeric: '136', code: '+1-345' },
    { name: 'Central African Republic', alpha2: 'CF', alpha3: 'CAF', numeric: '140', code: '+236' },
    { name: 'Chad', alpha2: 'TD', alpha3: 'TCD', numeric: '148', code: '+235' },
    { name: 'Chile', alpha2: 'CL', alpha3: 'CHL', numeric: '152', code: '+56' },
    { name: 'China', alpha2: 'CN', alpha3: 'CHN', numeric: '156', code: '+86' },
    { name: 'Christmas Island', alpha2: 'CX', alpha3: 'CXR', numeric: '162', code: '+61' },
    { name: 'Cocos (Keeling) Islands', alpha2: 'CC', alpha3: 'CCK', numeric: '166', code: '+61' },
    { name: 'Colombia', alpha2: 'CO', alpha3: 'COL', numeric: '170', code: '+57' },
    { name: 'Comoros', alpha2: 'KM', alpha3: 'COM', numeric: '174', code: '+269' },
    { name: 'Congo', alpha2: 'CG', alpha3: 'COG', numeric: '178', code: '+242' },
    { name: 'Congo (Democratic Republic of the)', alpha2: 'CD', alpha3: 'COD', numeric: '180', code: '+243' },
    { name: 'Cook Islands', alpha2: 'CK', alpha3: 'COK', numeric: '184', code: '+682' },
    { name: 'Costa Rica', alpha2: 'CR', alpha3: 'CRI', numeric: '188', code: '+506' },
    { name: 'Côte d\'Ivoire', alpha2: 'CI', alpha3: 'CIV', numeric: '384', code: '+225' },
    { name: 'Croatia', alpha2: 'HR', alpha3: 'HRV', numeric: '191', code: '+385' },
    { name: 'Cuba', alpha2: 'CU', alpha3: 'CUB', numeric: '192', code: '+53' },
    { name: 'Curaçao', alpha2: 'CW', alpha3: 'CUW', numeric: '531', code: '+599' },
    { name: 'Cyprus', alpha2: 'CY', alpha3: 'CYP', numeric: '196', code: '+357' },
    { name: 'Czechia', alpha2: 'CZ', alpha3: 'CZE', numeric: '203', code: '+420' },
    { name: 'Denmark', alpha2: 'DK', alpha3: 'DNK', numeric: '208', code: '+45' },
    { name: 'Djibouti', alpha2: 'DJ', alpha3: 'DJI', numeric: '262', code: '+253' },
    { name: 'Dominica', alpha2: 'DM', alpha3: 'DMA', numeric: '212', code: '+1-767' },
    { name: 'Dominican Republic', alpha2: 'DO', alpha3: 'DOM', numeric: '214', code: '+1-809' },
    { name: 'Ecuador', alpha2: 'EC', alpha3: 'ECU', numeric: '218', code: '+593' },
    { name: 'Egypt', alpha2: 'EG', alpha3: 'EGY', numeric: '818', code: '+20' },
    { name: 'El Salvador', alpha2: 'SV', alpha3: 'SLV', numeric: '222', code: '+503' },
    { name: 'Equatorial Guinea', alpha2: 'GQ', alpha3: 'GNQ', numeric: '226', code: '+240' },
    { name: 'Eritrea', alpha2: 'ER', alpha3: 'ERI', numeric: '232', code: '+291' },
    { name: 'Estonia', alpha2: 'EE', alpha3: 'EST', numeric: '233', code: '+372' },
    { name: 'Eswatini', alpha2: 'SZ', alpha3: 'SWZ', numeric: '748', code: '+268' },
    { name: 'Ethiopia', alpha2: 'ET', alpha3: 'ETH', numeric: '231', code: '+251' },
    { name: 'Falkland Islands (Malvinas)', alpha2: 'FK', alpha3: 'FLK', numeric: '238', code: '+500' },
    { name: 'Faroe Islands', alpha2: 'FO', alpha3: 'FRO', numeric: '234', code: '+298' },
    { name: 'Fiji', alpha2: 'FJ', alpha3: 'FJI', numeric: '242', code: '+679' },
    { name: 'Finland', alpha2: 'FI', alpha3: 'FIN', numeric: '246', code: '+358' },
    { name: 'France', alpha2: 'FR', alpha3: 'FRA', numeric: '250', code: '+33' },
    { name: 'French Guiana', alpha2: 'GF', alpha3: 'GUF', numeric: '254', code: '+594' },
    { name: 'French Polynesia', alpha2: 'PF', alpha3: 'PYF', numeric: '258', code: '+689' },
    { name: 'French Southern Territories', alpha2: 'TF', alpha3: 'ATF', numeric: '260', code: '+262' },
    { name: 'Gabon', alpha2: 'GA', alpha3: 'GAB', numeric: '266', code: '+241' },
    { name: 'Gambia', alpha2: 'GM', alpha3: 'GMB', numeric: '270', code: '+220' },
    { name: 'Georgia', alpha2: 'GE', alpha3: 'GEO', numeric: '268', code: '+995' },
    { name: 'Germany', alpha2: 'DE', alpha3: 'DEU', numeric: '276', code: '+49' },
    { name: 'Ghana', alpha2: 'GH', alpha3: 'GHA', numeric: '288', code: '+233' },
    { name: 'Gibraltar', alpha2: 'GI', alpha3: 'GIB', numeric: '292', code: '+350' },
    { name: 'Greece', alpha2: 'GR', alpha3: 'GRC', numeric: '300', code: '+30' },
    { name: 'Greenland', alpha2: 'GL', alpha3: 'GRL', numeric: '304', code: '+299' },
    { name: 'Grenada', alpha2: 'GD', alpha3: 'GRD', numeric: '308', code: '+1-473' },
    { name: 'Guadeloupe', alpha2: 'GP', alpha3: 'GLP', numeric: '312', code: '+590' },
    { name: 'Guam', alpha2: 'GU', alpha3: 'GUM', numeric: '316', code: '+1-671' },
    { name: 'Guatemala', alpha2: 'GT', alpha3: 'GTM', numeric: '320', code: '+502' },
    { name: 'Guernsey', alpha2: 'GG', alpha3: 'GGY', numeric: '831', code: '+44-1481' },
    { name: 'Guinea', alpha2: 'GN', alpha3: 'GIN', numeric: '324', code: '+224' },
    { name: 'Guinea-Bissau', alpha2: 'GW', alpha3: 'GNB', numeric: '624', code: '+245' },
    { name: 'Guyana', alpha2: 'GY', alpha3: 'GUY', numeric: '328', code: '+592' },
    { name: 'Haiti', alpha2: 'HT', alpha3: 'HTI', numeric: '332', code: '+509' },
    { name: 'Heard Island and McDonald Islands', alpha2: 'HM', alpha3: 'HMD', numeric: '334', code: '' },
    { name: 'Holy See', alpha2: 'VA', alpha3: 'VAT', numeric: '336', code: '+379' },
    { name: 'Honduras', alpha2: 'HN', alpha3: 'HND', numeric: '340', code: '+504' },
    { name: 'Hong Kong', alpha2: 'HK', alpha3: 'HKG', numeric: '344', code: '+852' },
    { name: 'Hungary', alpha2: 'HU', alpha3: 'HUN', numeric: '348', code: '+36' },
    { name: 'Iceland', alpha2: 'IS', alpha3: 'ISL', numeric: '352', code: '+354' },
    { name: 'India', alpha2: 'IN', alpha3: 'IND', numeric: '356', code: '+91' },
    { name: 'Indonesia', alpha2: 'ID', alpha3: 'IDN', numeric: '360', code: '+62' },
    { name: 'Iran (Islamic Republic of)', alpha2: 'IR', alpha3: 'IRN', numeric: '364', code: '+98' },
    { name: 'Iraq', alpha2: 'IQ', alpha3: 'IRQ', numeric: '368', code: '+964' },
    { name: 'Ireland', alpha2: 'IE', alpha3: 'IRL', numeric: '372', code: '+353' },
    { name: 'Isle of Man', alpha2: 'IM', alpha3: 'IMN', numeric: '833', code: '+44-1624' },
    { name: 'Israel', alpha2: 'IL', alpha3: 'ISR', numeric: '376', code: '+972' },
    { name: 'Italy', alpha2: 'IT', alpha3: 'ITA', numeric: '380', code: '+39' },
    { name: 'Jamaica', alpha2: 'JM', alpha3: 'JAM', numeric: '388', code: '+1-876' },
    { name: 'Japan', alpha2: 'JP', alpha3: 'JPN', numeric: '392', code: '+81' },
    { name: 'Jersey', alpha2: 'JE', alpha3: 'JEY', numeric: '832', code: '+44-1534' },
    { name: 'Jordan', alpha2: 'JO', alpha3: 'JOR', numeric: '400', code: '+962' },
    { name: 'Kazakhstan', alpha2: 'KZ', alpha3: 'KAZ', numeric: '398', code: '+7' },
    { name: 'Kenya', alpha2: 'KE', alpha3: 'KEN', numeric: '404', code: '+254' },
    { name: 'Kiribati', alpha2: 'KI', alpha3: 'KIR', numeric: '296', code: '+686' },
    { name: 'Korea (Democratic People\'s Republic of)', alpha2: 'KP', alpha3: 'PRK', numeric: '408', code: '+850' },
    { name: 'Korea (Republic of)', alpha2: 'KR', alpha3: 'KOR', numeric: '410', code: '+82' },
    { name: 'Kuwait', alpha2: 'KW', alpha3: 'KWT', numeric: '414', code: '+965' },
    { name: 'Kyrgyzstan', alpha2: 'KG', alpha3: 'KGZ', numeric: '417', code: '+996' },
    { name: 'Lao People\'s Democratic Republic', alpha2: 'LA', alpha3: 'LAO', numeric: '418', code: '+856' },
    { name: 'Latvia', alpha2: 'LV', alpha3: 'LVA', numeric: '428', code: '+371' },
    { name: 'Lebanon', alpha2: 'LB', alpha3: 'LBN', numeric: '422', code: '+961' },
    { name: 'Lesotho', alpha2: 'LS', alpha3: 'LSO', numeric: '426', code: '+266' },
    { name: 'Liberia', alpha2: 'LR', alpha3: 'LBR', numeric: '430', code: '+231' },
    { name: 'Libya', alpha2: 'LY', alpha3: 'LBY', numeric: '434', code: '+218' },
    { name: 'Liechtenstein', alpha2: 'LI', alpha3: 'LIE', numeric: '438', code: '+423' },
    { name: 'Lithuania', alpha2: 'LT', alpha3: 'LTU', numeric: '440', code: '+370' },
    { name: 'Luxembourg', alpha2: 'LU', alpha3: 'LUX', numeric: '442', code: '+352' },
    { name: 'Macao', alpha2: 'MO', alpha3: 'MAC', numeric: '446', code: '+853' },
    { name: 'Madagascar', alpha2: 'MG', alpha3: 'MDG', numeric: '450', code: '+261' },
    { name: 'Malawi', alpha2: 'MW', alpha3: 'MWI', numeric: '454', code: '+265' },
    { name: 'Malaysia', alpha2: 'MY', alpha3: 'MYS', numeric: '458', code: '+60' },
    { name: 'Maldives', alpha2: 'MV', alpha3: 'MDV', numeric: '462', code: '+960' },
    { name: 'Mali', alpha2: 'ML', alpha3: 'MLI', numeric: '466', code: '+223' },
    { name: 'Malta', alpha2: 'MT', alpha3: 'MLT', numeric: '470', code: '+356' },
    { name: 'Marshall Islands', alpha2: 'MH', alpha3: 'MHL', numeric: '584', code: '+692' },
    { name: 'Martinique', alpha2: 'MQ', alpha3: 'MTQ', numeric: '474', code: '+596' },
    { name: 'Mauritania', alpha2: 'MR', alpha3: 'MRT', numeric: '478', code: '+222' },
    { name: 'Mauritius', alpha2: 'MU', alpha3: 'MUS', numeric: '480', code: '+230' },
    { name: 'Mayotte', alpha2: 'YT', alpha3: 'MYT', numeric: '175', code: '+262' },
    { name: 'Mexico', alpha2: 'MX', alpha3: 'MEX', numeric: '484', code: '+52' },
    { name: 'Micronesia (Federated States of)', alpha2: 'FM', alpha3: 'FSM', numeric: '583', code: '+691' },
    { name: 'Moldova (Republic of)', alpha2: 'MD', alpha3: 'MDA', numeric: '498', code: '+373' },
    { name: 'Monaco', alpha2: 'MC', alpha3: 'MCO', numeric: '492', code: '+377' },
    { name: 'Mongolia', alpha2: 'MN', alpha3: 'MNG', numeric: '496', code: '+976' },
    { name: 'Montenegro', alpha2: 'ME', alpha3: 'MNE', numeric: '499', code: '+382' },
    { name: 'Montserrat', alpha2: 'MS', alpha3: 'MSR', numeric: '500', code: '+1-664' },
    { name: 'Morocco', alpha2: 'MA', alpha3: 'MAR', numeric: '504', code: '+212' },
    { name: 'Mozambique', alpha2: 'MZ', alpha3: 'MOZ', numeric: '508', code: '+258' },
    { name: 'Myanmar', alpha2: 'MM', alpha3: 'MMR', numeric: '104', code: '+95' },
    { name: 'Namibia', alpha2: 'NA', alpha3: 'NAM', numeric: '516', code: '+264' },
    { name: 'Nauru', alpha2: 'NR', alpha3: 'NRU', numeric: '520', code: '+674' },
    { name: 'Nepal', alpha2: 'NP', alpha3: 'NPL', numeric: '524', code: '+977' },
    { name: 'Netherlands', alpha2: 'NL', alpha3: 'NLD', numeric: '528', code: '+31' },
    { name: 'New Caledonia', alpha2: 'NC', alpha3: 'NCL', numeric: '540', code: '+687' },
    { name: 'New Zealand', alpha2: 'NZ', alpha3: 'NZL', numeric: '554', code: '+64' },
    { name: 'Nicaragua', alpha2: 'NI', alpha3: 'NIC', numeric: '558', code: '+505' },
    { name: 'Niger', alpha2: 'NE', alpha3: 'NER', numeric: '562', code: '+227' },
    { name: 'Nigeria', alpha2: 'NG', alpha3: 'NGA', numeric: '566', code: '+234' },
    { name: 'Niue', alpha2: 'NU', alpha3: 'NIU', numeric: '570', code: '+683' },
    { name: 'Norfolk Island', alpha2: 'NF', alpha3: 'NFK', numeric: '574', code: '+672' },
    { name: 'North Macedonia', alpha2: 'MK', alpha3: 'MKD', numeric: '807', code: '+389' },
    { name: 'Northern Mariana Islands', alpha2: 'MP', alpha3: 'MNP', numeric: '580', code: '+1-670' },
    { name: 'Norway', alpha2: 'NO', alpha3: 'NOR', numeric: '578', code: '+47' },
    { name: 'Oman', alpha2: 'OM', alpha3: 'OMN', numeric: '512', code: '+968' },
    { name: 'Pakistan', alpha2: 'PK', alpha3: 'PAK', numeric: '586', code: '+92' },
    { name: 'Palau', alpha2: 'PW', alpha3: 'PLW', numeric: '585', code: '+680' },
    { name: 'Palestine, State of', alpha2: 'PS', alpha3: 'PSE', numeric: '275', code: '+970' },
    { name: 'Panama', alpha2: 'PA', alpha3: 'PAN', numeric: '591', code: '+507' },
    { name: 'Papua New Guinea', alpha2: 'PG', alpha3: 'PNG', numeric: '598', code: '+675' },
    { name: 'Paraguay', alpha2: 'PY', alpha3: 'PRY', numeric: '600', code: '+595' },
    { name: 'Peru', alpha2: 'PE', alpha3: 'PER', numeric: '604', code: '+51' },
    { name: 'Philippines', alpha2: 'PH', alpha3: 'PHL', numeric: '608', code: '+63' },
    { name: 'Pitcairn', alpha2: 'PN', alpha3: 'PCN', numeric: '612', code: '+870' },
    { name: 'Poland', alpha2: 'PL', alpha3: 'POL', numeric: '616', code: '+48' },
    { name: 'Portugal', alpha2: 'PT', alpha3: 'PRT', numeric: '620', code: '+351' },
    { name: 'Puerto Rico', alpha2: 'PR', alpha3: 'PRI', numeric: '630', code: '+1-787' },
    { name: 'Qatar', alpha2: 'QA', alpha3: 'QAT', numeric: '634', code: '+974' },
    { name: 'Réunion', alpha2: 'RE', alpha3: 'REU', numeric: '638', code: '+262' },
    { name: 'Romania', alpha2: 'RO', alpha3: 'ROU', numeric: '642', code: '+40' },
    { name: 'Russian Federation', alpha2: 'RU', alpha3: 'RUS', numeric: '643', code: '+7' },
    { name: 'Rwanda', alpha2: 'RW', alpha3: 'RWA', numeric: '646', code: '+250' },
    { name: 'Saint Barthélemy', alpha2: 'BL', alpha3: 'BLM', numeric: '652', code: '+590' },
    { name: 'Saint Helena, Ascension and Tristan da Cunha', alpha2: 'SH', alpha3: 'SHN', numeric: '654', code: '+290' },
    { name: 'Saint Kitts and Nevis', alpha2: 'KN', alpha3: 'KNA', numeric: '659', code: '+1-869' },
    { name: 'Saint Lucia', alpha2: 'LC', alpha3: 'LCA', numeric: '662', code: '+1-758' },
    { name: 'Saint Martin (French part)', alpha2: 'MF', alpha3: 'MAF', numeric: '663', code: '+590' },
    { name: 'Saint Pierre and Miquelon', alpha2: 'PM', alpha3: 'SPM', numeric: '666', code: '+508' },
    { name: 'Saint Vincent and the Grenadines', alpha2: 'VC', alpha3: 'VCT', numeric: '670', code: '+1-784' },
    { name: 'Samoa', alpha2: 'WS', alpha3: 'WSM', numeric: '882', code: '+685' },
    { name: 'San Marino', alpha2: 'SM', alpha3: 'SMR', numeric: '674', code: '+378' },
    { name: 'Sao Tome and Principe', alpha2: 'ST', alpha3: 'STP', numeric: '678', code: '+239' },
    { name: 'Saudi Arabia', alpha2: 'SA', alpha3: 'SAU', numeric: '682', code: '+966' },
    { name: 'Senegal', alpha2: 'SN', alpha3: 'SEN', numeric: '686', code: '+221' },
    { name: 'Serbia', alpha2: 'RS', alpha3: 'SRB', numeric: '688', code: '+381' },
    { name: 'Seychelles', alpha2: 'SC', alpha3: 'SYC', numeric: '690', code: '+248' },
    { name: 'Sierra Leone', alpha2: 'SL', alpha3: 'SLE', numeric: '694', code: '+232' },
    { name: 'Singapore', alpha2: 'SG', alpha3: 'SGP', numeric: '702', code: '+65' },
    { name: 'Sint Maarten (Dutch part)', alpha2: 'SX', alpha3: 'SXM', numeric: '534', code: '+1-721' },
    { name: 'Slovakia', alpha2: 'SK', alpha3: 'SVK', numeric: '703', code: '+421' },
    { name: 'Slovenia', alpha2: 'SI', alpha3: 'SVN', numeric: '705', code: '+386' },
    { name: 'Solomon Islands', alpha2: 'SB', alpha3: 'SLB', numeric: '090', code: '+677' },
    { name: 'Somalia', alpha2: 'SO', alpha3: 'SOM', numeric: '706', code: '+252' },
    { name: 'South Africa', alpha2: 'ZA', alpha3: 'ZAF', numeric: '710', code: '+27' },
    { name: 'South Georgia and the South Sandwich Islands', alpha2: 'GS', alpha3: 'SGS', numeric: '239', code: '+500' },
    { name: 'South Sudan', alpha2: 'SS', alpha3: 'SSD', numeric: '728', code: '+211' },
    { name: 'Spain', alpha2: 'ES', alpha3: 'ESP', numeric: '724', code: '+34' },
    { name: 'Sri Lanka', alpha2: 'LK', alpha3: 'LKA', numeric: '144', code: '+94' },
    { name: 'Sudan', alpha2: 'SD', alpha3: 'SDN', numeric: '729', code: '+249' },
    { name: 'Suriname', alpha2: 'SR', alpha3: 'SUR', numeric: '740', code: '+597' },
    { name: 'Svalbard and Jan Mayen', alpha2: 'SJ', alpha3: 'SJM', numeric: '744', code: '+47' },
    { name: 'Sweden', alpha2: 'SE', alpha3: 'SWE', numeric: '752', code: '+46' },
    { name: 'Switzerland', alpha2: 'CH', alpha3: 'CHE', numeric: '756', code: '+41' },
    { name: 'Syrian Arab Republic', alpha2: 'SY', alpha3: 'SYR', numeric: '760', code: '+963' },
    { name: 'Taiwan, Province of China', alpha2: 'TW', alpha3: 'TWN', numeric: '158', code: '+886' },
    { name: 'Tajikistan', alpha2: 'TJ', alpha3: 'TJK', numeric: '762', code: '+992' },
    { name: 'Tanzania, United Republic of', alpha2: 'TZ', alpha3: 'TZA', numeric: '834', code: '+255' },
    { name: 'Thailand', alpha2: 'TH', alpha3: 'THA', numeric: '764', code: '+66' },
    { name: 'Timor-Leste', alpha2: 'TL', alpha3: 'TLS', numeric: '626', code: '+670' },
    { name: 'Togo', alpha2: 'TG', alpha3: 'TGO', numeric: '768', code: '+228' },
    { name: 'Tokelau', alpha2: 'TK', alpha3: 'TKL', numeric: '772', code: '+690' },
    { name: 'Tonga', alpha2: 'TO', alpha3: 'TON', numeric: '776', code: '+676' },
    { name: 'Trinidad and Tobago', alpha2: 'TT', alpha3: 'TTO', numeric: '780', code: '+1-868' },
    { name: 'Tunisia', alpha2: 'TN', alpha3: 'TUN', numeric: '788', code: '+216' },
    { name: 'Turkey', alpha2: 'TR', alpha3: 'TUR', numeric: '792', code: '+90' },
    { name: 'Turkmenistan', alpha2: 'TM', alpha3: 'TKM', numeric: '795', code: '+993' },
    { name: 'Turks and Caicos Islands', alpha2: 'TC', alpha3: 'TCA', numeric: '796', code: '+1-649' },
    { name: 'Tuvalu', alpha2: 'TV', alpha3: 'TUV', numeric: '798', code: '+688' },
    { name: 'Uganda', alpha2: 'UG', alpha3: 'UGA', numeric: '800', code: '+256' },
    { name: 'Ukraine', alpha2: 'UA', alpha3: 'UKR', numeric: '804', code: '+380' },
    { name: 'United Arab Emirates', alpha2: 'AE', alpha3: 'ARE', numeric: '784', code: '+971' },
    { name: 'United Kingdom of Great Britain and Northern Ireland', alpha2: 'GB', alpha3: 'GBR', numeric: '826', code: '+44' },
    { name: 'United States of America', alpha2: 'US', alpha3: 'USA', numeric: '840', code: '+1' },
    { name: 'United States Minor Outlying Islands', alpha2: 'UM', alpha3: 'UMI', numeric: '581', code: '' },
    { name: 'Uruguay', alpha2: 'UY', alpha3: 'URY', numeric: '858', code: '+598' },
    { name: 'Uzbekistan', alpha2: 'UZ', alpha3: 'UZB', numeric: '860', code: '+998' },
    { name: 'Vanuatu', alpha2: 'VU', alpha3: 'VUT', numeric: '548', code: '+678' },
    { name: 'Venezuela (Bolivarian Republic of)', alpha2: 'VE', alpha3: 'VEN', numeric: '862', code: '+58' },
    { name: 'Viet Nam', alpha2: 'VN', alpha3: 'VNM', numeric: '704', code: '+84' },
    { name: 'Virgin Islands (British)', alpha2: 'VG', alpha3: 'VGB', numeric: '092', code: '+1-284' },
    { name: 'Virgin Islands (U.S.)', alpha2: 'VI', alpha3: 'VIR', numeric: '850', code: '+1-340' },
    { name: 'Wallis and Futuna', alpha2: 'WF', alpha3: 'WLF', numeric: '876', code: '+681' },
    { name: 'Western Sahara', alpha2: 'EH', alpha3: 'ESH', numeric: '732', code: '+212' },
    { name: 'Yemen', alpha2: 'YE', alpha3: 'YEM', numeric: '887', code: '+967' },
    { name: 'Zambia', alpha2: 'ZM', alpha3: 'ZMB', numeric: '894', code: '+260' },
    { name: 'Zimbabwe', alpha2: 'ZW', alpha3: 'ZWE', numeric: '716', code: '+263' }
];