version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: nove-postgres
    environment:
      POSTGRES_DB: pm_platform
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:


