import { ISelectOption } from "src/types/common";

export const NOC_CODES_DATA: ISelectOption[] = [
    { label: "Human resources managers", value: 10011 },
    { label: "Purchasing managers", value: 10012 },
    { label: "Other administrative services managers", value: 10019 },
    { label: "Insurance, real estate and financial brokerage managers", value: 10020 },
    { label: "Banking, credit and other investment managers", value: 10021 },
    { label: "Advertising, marketing and public relations managers", value: 10022 },
    { label: "Other business services managers", value: 10029 },
    { label: "Telecommunication carriers managers", value: 10030 },
    { label: "Engineering managers", value: 20010 },
    { label: "Architecture and science managers", value: 20011 },
    { label: "Computer and information systems managers", value: 20012 },
    { label: "Managers in health care", value: 30010 },
    { label: "Government managers - health and social policy development and program administration", value: 40010 },
    { label: "Government managers - economic analysis, policy development and program administration", value: 40011 },
    { label: "Government managers - education policy development and program administration", value: 40012 },
    { label: "Other managers in public administration", value: 40019 },
    { label: "Administrators - post-secondary education and vocational training", value: 40020 },
    { label: "School principals and administrators of elementary and secondary education", value: 40021 },
    { label: "Managers in social, community and correctional services", value: 40030 },
    { label: "Commissioned police officers and related occupations in public protection services", value: 40040 },
    { label: "Fire chiefs and senior firefighting officers", value: 40041 },
    { label: "Commissioned officers of the Canadian Armed Forces", value: 40042 },
    { label: "Library, archive, museum and art gallery managers", value: 50010 },
    { label: "Managers - publishing, motion pictures, broadcasting and performing arts", value: 50011 },
    { label: "Recreation, sports and fitness program and service directors", value: 50012 },
    { label: "Corporate sales managers", value: 60010 },
    { label: "Retail and wholesale trade managers", value: 60020 },
    { label: "Restaurant and food service managers", value: 60030 },
    { label: "Accommodation service managers", value: 60031 },
    { label: "Managers in customer and personal services", value: 60040 },
    { label: "Construction managers", value: 70010 },
    { label: "Home building and renovation managers", value: 70011 },
    { label: "Facility operation and maintenance managers", value: 70012 },
    { label: "Managers in transportation", value: 70020 },
    { label: "Postal and courier services managers", value: 70021 },
    { label: "Managers in natural resources production and fishing", value: 80010 },
    { label: "Managers in agriculture", value: 80020 },
    { label: "Managers in horticulture", value: 80021 },
    { label: "Managers in aquaculture", value: 80022 },
    { label: "Manufacturing managers", value: 90010 },
    { label: "Utilities managers", value: 90011 },
    { label: "Financial auditors and accountants", value: 11100 },
    { label: "Financial and investment analysts", value: 11101 },
    { label: "Financial advisors", value: 11102 },
    { label: "Securities agents, investment dealers and brokers", value: 11103 },
    { label: "Other financial officers", value: 11109 },
    { label: "Human resources professionals", value: 11200 },
    { label: "Professional occupations in business management consulting", value: 11201 },
    { label: "Professional occupations in advertising, marketing and public relations", value: 11202 },
    { label: "Physicists and astronomers", value: 21100 },
    { label: "Chemists", value: 21101 },
    { label: "Geoscientists and oceanographers", value: 21102 },
    { label: "Meteorologists and climatologists", value: 21103 },
    { label: "Other professional occupations in physical sciences", value: 21109 },
    { label: "Biologists and related scientists", value: 21110 },
    { label: "Forestry professionals", value: 21111 },
    { label: "Agricultural representatives, consultants and specialists", value: 21112 },
    { label: "Public and environmental health and safety professionals", value: 21120 },
    { label: "Architects", value: 21200 },
    { label: "Landscape architects", value: 21201 },
    { label: "Urban and land use planners", value: 21202 },
    { label: "Land surveyors", value: 21203 },
    { label: "Mathematicians, statisticians and actuaries", value: 21210 },
    { label: "Data scientists", value: 21211 },
    { label: "Cybersecurity specialists", value: 21220 },
    { label: "Business systems specialists", value: 21221 },
    { label: "Information systems specialists", value: 21222 },
    { label: "Database analysts and data administrators", value: 21223 },
    { label: "Computer systems developers and programmers", value: 21230 },
    { label: "Software engineers and designers", value: 21231 },
    { label: "Software developers and programmers", value: 21232 },
    { label: "Web designers", value: 21233 },
    { label: "Web developers and programmers", value: 21234 },
    { label: "Civil engineers", value: 21300 },
    { label: "Mechanical engineers", value: 21301 },
    { label: "Electrical and electronics engineers", value: 21310 },
    { label: "Computer engineers (except software engineers and designers)", value: 21311 },
    { label: "Chemical engineers", value: 21320 },
    { label: "Industrial and manufacturing engineers", value: 21321 },
    { label: "Metallurgical and materials engineers", value: 21322 },
    { label: "Mining engineers", value: 21330 },
    { label: "Geological engineers", value: 21331 },
    { label: "Petroleum engineers", value: 21332 },
    { label: "Aerospace engineers", value: 21390 },
    { label: "Other professional engineers", value: 21399 },
    { label: "Specialists in clinical and laboratory medicine", value: 31100 },
    { label: "Specialists in surgery", value: 31101 },
    { label: "General practitioners and family physicians", value: 31102 },
    { label: "Veterinarians", value: 31103 },
    { label: "Dentists", value: 31110 },
    { label: "Optometrists", value: 31111 },
    { label: "Audiologists and speech-language pathologists", value: 31112 },
    { label: "Pharmacists", value: 31120 },
    { label: "Dietitians and nutritionists", value: 31121 },
    { label: "Psychologists", value: 31200 },
    { label: "Chiropractors", value: 31201 },
    { label: "Physiotherapists", value: 31202 },
    { label: "Occupational therapists", value: 31203 },
    { label: "Kinesiologists and other professional occupations in therapy and assessment", value: 31204 },
    { label: "Other professional occupations in health diagnosing and treating", value: 31209 },
    { label: "Nursing coordinators and supervisors", value: 31300 },
    { label: "Registered nurses and registered psychiatric nurses", value: 31301 },
    { label: "Nurse practitioners", value: 31302 },
    { label: "Physician assistants, midwives and allied health professionals", value: 31303 },
    { label: "Judges", value: 41100 },
    { label: "Lawyers and Quebec notaries", value: 41101 },
    { label: "University professors and lecturers", value: 41200 },
    { label: "Post-secondary teaching and research assistants", value: 41201 },
    { label: "College and other vocational instructors", value: 41210 },
    { label: "Secondary school teachers", value: 41220 },
    { label: "Elementary school and kindergarten teachers", value: 41221 },
    { label: "Social workers", value: 41300 },
    { label: "Therapists in counselling and related specialized therapies", value: 41301 },
    { label: "Religious leaders", value: 41302 },
    { label: "Police investigators and other investigative occupations", value: 41310 },
    { label: "Probation and parole officers", value: 41311 },
    { label: "Educational counsellors", value: 41320 },
    { label: "Career development practitioners and career counsellors (except education)", value: 41321 },
    { label: "Natural and applied science policy researchers, consultants and program officers", value: 41400 },
    { label: "Economists and economic policy researchers and analysts", value: 41401 },
    { label: "Business development officers and market researchers and analysts", value: 41402 },
    { label: "Social policy researchers, consultants and program officers", value: 41403 },
    { label: "Health policy researchers, consultants and program officers", value: 41404 },
    { label: "Education policy researchers, consultants and program officers", value: 41405 },
    { label: "Recreation, sports and fitness policy researchers, consultants and program officers", value: 41406 },
    { label: "Program officers unique to government", value: 41407 },
    { label: "Other professional occupations in social science", value: 41409 },
    { label: "Librarians", value: 51100 },
    { label: "Conservators and curators", value: 51101 },
    { label: "Archivists", value: 51102 },
    { label: "Editors", value: 51110 },
    { label: "Authors and writers (except technical)", value: 51111 },
    { label: "Technical writers", value: 51112 },
    { label: "Journalists", value: 51113 },
    { label: "Translators, terminologists and interpreters", value: 51114 },
    { label: "Producers, directors, choreographers and related occupations", value: 51120 },
    { label: "Conductors, composers and arrangers", value: 51121 },
    { label: "Musicians and singers", value: 51122 },
    { label: "Supervisors, general office and administrative support workers", value: 12010 },
    { label: "Supervisors, finance and insurance office workers", value: 12011 },
    { label: "Supervisors, library, correspondence and related information workers", value: 12012 },
    { label: "Supervisors, supply chain, tracking and scheduling coordination occupations", value: 12013 },
    { label: "Executive assistants", value: 12100 },
    { label: "Human resources and recruitment officers", value: 12101 },
    { label: "Procurement and purchasing agents and officers", value: 12102 },
    { label: "Conference and event planners", value: 12103 },
    { label: "Employment insurance and revenue officers", value: 12104 },
    { label: "Court reporters, medical transcriptionists and related occupations", value: 12110 },
    { label: "Health information management occupations", value: 12111 },
    { label: "Records management technicians", value: 12112 },
    { label: "Statistical officers and related research support occupations", value: 12113 },
    { label: "Accounting technicians and bookkeepers", value: 12200 },
    { label: "Insurance adjusters and claims examiners", value: 12201 },
    { label: "Insurance underwriters", value: 12202 },
    { label: "Assessors, business valuators and appraisers", value: 12203 },
    { label: "Chemical technologists and technicians", value: 22100 },
    { label: "Geological and mineral technologists and technicians", value: 22101 },
    { label: "Biological technologists and technicians", value: 22110 },
    { label: "Agricultural and fish products inspectors", value: 22111 },
    { label: "Forestry technologists and technicians", value: 22112 },
    { label: "Conservation and fishery officers", value: 22113 },
    { label: "Landscape and horticulture technicians and specialists", value: 22114 },
    { label: "Architectural technologists and technicians", value: 22210 },
    { label: "Industrial designers", value: 22211 },
    { label: "Drafting technologists and technicians", value: 22212 },
    { label: "Land survey technologists and technicians", value: 22213 },
    { label: "Technical occupations in geomatics and meteorology", value: 22214 },
    { label: "Computer network and web technicians", value: 22220 },
    { label: "User support technicians", value: 22221 },
    { label: "Information systems testing technicians", value: 22222 },
    { label: "Non-destructive testers and inspectors", value: 22230 },
    { label: "Engineering inspectors and regulatory officers", value: 22231 },
    { label: "Occupational health and safety specialists", value: 22232 },
    { label: "Construction inspectors", value: 22233 },
    { label: "Civil engineering technologists and technicians", value: 22300 },
    { label: "Mechanical engineering technologists and technicians", value: 22301 },
    { label: "Industrial engineering and manufacturing technologists and technicians", value: 22302 },
    { label: "Construction estimators", value: 22303 },
    { label: "Electrical and electronics engineering technologists and technicians", value: 22310 },
    { label: "Electronic service technicians (household and business equipment)", value: 22311 },
    { label: "Industrial instrument technicians and mechanics", value: 22312 },
    { label: "Aircraft instrument, electrical and avionics mechanics, technicians and inspectors", value: 22313 },
    { label: "Opticians", value: 32100 },
    { label: "Licensed practical nurses", value: 32101 },
    { label: "Paramedical occupations", value: 32102 },
    { label: "Respiratory therapists, clinical perfusionists and cardiopulmonary technologists", value: 32103 },
    { label: "Animal health technologists and veterinary technicians", value: 32104 },
    { label: "Other technical occupations in therapy and assessment", value: 32109 },
    { label: "Denturists", value: 32110 },
    { label: "Dental hygienists and dental therapists", value: 32111 },
    { label: "Dental technologists and technicians", value: 32112 },
    { label: "Medical laboratory technologists", value: 32120 },
    { label: "Medical radiation technologists", value: 32121 },
    { label: "Medical sonographers", value: 32122 },
    { label: "Cardiology technologists and electrophysiological diagnostic technologists", value: 32123 },
    { label: "Pharmacy technicians", value: 32124 },
    { label: "Other medical technologists and technicians", value: 32129 },
    { label: "Traditional Chinese medicine practitioners and acupuncturists", value: 32200 },
    { label: "Massage therapists", value: 32201 },
    { label: "Other practitioners of natural healing", value: 32209 },
    { label: "Police officers (except commissioned)", value: 42100 },
    { label: "Firefighters", value: 42101 },
    { label: "Specialized members of the Canadian Armed Forces", value: 42102 },
    { label: "Paralegals and related occupations", value: 42200 },
    { label: "Social and community service workers", value: 42201 },
    { label: "Early childhood educators and assistants", value: 42202 },
    { label: "Instructors of persons with disabilities", value: 42203 },
    { label: "Religion workers", value: 42204 },
    { label: "Library and public archive technicians", value: 52100 },
    { label: "Film and video camera operators", value: 52110 },
    { label: "Graphic arts technicians", value: 52111 },
    { label: "Broadcast technicians", value: 52112 },
    { label: "Audio and video recording technicians", value: 52113 },
    { label: "Announcers and other broadcasters", value: 52114 },
    { label: "Other technical and coordinating occupations in motion pictures, broadcasting and the performing arts", value: 52119 },
    { label: "Graphic designers and illustrators", value: 52120 },
    { label: "Interior designers and interior decorators", value: 52121 },
    { label: "Retail sales supervisors", value: 62010 },
    { label: "Food service supervisors", value: 62020 },
    { label: "Executive housekeepers", value: 62021 },
    { label: "Accommodation, travel, tourism and related services supervisors", value: 62022 },
    { label: "Customer and information services supervisors", value: 62023 },
    { label: "Cleaning supervisors", value: 62024 },
    { label: "Other services supervisors", value: 62029 },
    { label: "Technical sales specialists - wholesale trade", value: 62100 },
    { label: "Retail and wholesale buyers", value: 62101 },
    { label: "Chefs", value: 62200 },
    { label: "Funeral directors and embalmers", value: 62201 },
    { label: "Jewellers, jewellery and watch repairers and related occupations", value: 62202 },
    { label: "Contractors and supervisors, machining, metal forming, shaping and erecting trades and related occupations", value: 72010 },
    { label: "Contractors and supervisors, electrical trades and telecommunications occupations", value: 72011 },
    { label: "Contractors and supervisors, pipefitting trades", value: 72012 },
    { label: "Contractors and supervisors, carpentry trades", value: 72013 },
    { label: "Contractors and supervisors, other construction trades, installers, repairers and servicers", value: 72014 },
    { label: "Contractors and supervisors, mechanic trades", value: 72020 },
    { label: "Contractors and supervisors, heavy equipment operator crews", value: 72021 },
    { label: "Supervisors, printing and related occupations", value: 72022 },
    { label: "Supervisors, railway transport operations", value: 72023 },
    { label: "Supervisors, motor transport and other ground transit operators", value: 72024 },
    { label: "Supervisors, mail and message distribution occupations", value: 72025 },
    { label: "Machinists and machining and tooling inspectors", value: 72100 },
    { label: "Tool and die makers", value: 72101 },
    { label: "Sheet metal workers", value: 72102 },
    { label: "Boilermakers", value: 72103 },
    { label: "Structural metal and platework fabricators and fitters", value: 72104 },
    { label: "Ironworkers", value: 72105 },
    { label: "Welders and related machine operators", value: 72106 },
    { label: "Electricians (except industrial and power system)", value: 72200 },
    { label: "Industrial electricians", value: 72201 },
    { label: "Power system electricians", value: 72202 },
    { label: "Electrical power line and cable workers", value: 72203 },
    { label: "Telecommunications line and cable installers and repairers", value: 72204 },
    { label: "Telecommunications equipment installation and cable television service technicians", value: 72205 },
    { label: "Plumbers", value: 72300 },
    { label: "Steamfitters, pipefitters and sprinkler system installers", value: 72301 },
    { label: "Gas fitters", value: 72302 },
    { label: "Carpenters", value: 72310 },
    { label: "Cabinetmakers", value: 72311 },
    { label: "Bricklayers", value: 72320 },
    { label: "Insulators", value: 72321 },
    { label: "Construction millwrights and industrial mechanics", value: 72400 },
    { label: "Heavy-duty equipment mechanics", value: 72401 },
    { label: "Heating, refrigeration and air conditioning mechanics", value: 72402 },
    { label: "Railway carmen/women", value: 72403 },
    { label: "Aircraft mechanics and aircraft inspectors", value: 72404 },
    { label: "Machine fitters", value: 72405 },
    { label: "Elevator constructors and mechanics", value: 72406 },
    { label: "Automotive service technicians, truck and bus mechanics and mechanical repairers", value: 72410 },
    { label: "Auto body collision, refinishing and glass technicians and damage repair estimators", value: 72411 },
    { label: "Oil and solid fuel heating mechanics", value: 72420 },
    { label: "Appliance servicers and repairers", value: 72421 },
    { label: "Electrical mechanics", value: 72422 },
    { label: "Motorcycle, all-terrain vehicle and other related mechanics", value: 72423 },
    { label: "Other small engine and small equipment repairers", value: 72429 },
    { label: "Crane operators", value: 72500 },
    { label: "Water well drillers", value: 72501 },
    { label: "Air pilots, flight engineers and flying instructors", value: 72600 },
    { label: "Air traffic controllers and related occupations", value: 72601 },
    { label: "Deck officers, water transport", value: 72602 },
    { label: "Engineer officers, water transport", value: 72603 },
    { label: "Railway traffic controllers and marine traffic regulators", value: 72604 },
    { label: "Other technical trades and related occupations", value: 72999 },
    { label: "Supervisors, logging and forestry", value: 82010 },
    { label: "Supervisors, mining and quarrying", value: 82020 },
    { label: "Contractors and supervisors, oil and gas drilling and services", value: 82021 },
    { label: "Agricultural service contractors and farm supervisors", value: 82030 },
    { label: "Contractors and supervisors, landscaping, grounds maintenance and horticulture services", value: 82031 },
    { label: "Supervisors, mineral and metal processing", value: 92010 },
    { label: "Supervisors, petroleum, gas and chemical processing and utilities", value: 92011 },
    { label: "Supervisors, food and beverage processing", value: 92012 },
    { label: "Supervisors, plastic and rubber products manufacturing", value: 92013 },
    { label: "Supervisors, forest products processing", value: 92014 },
    { label: "Supervisors, textile, fabric, fur and leather products processing and manufacturing", value: 92015 },
    { label: "Supervisors, motor vehicle assembling", value: 92020 },
    { label: "Supervisors, electronics and electrical products manufacturing", value: 92021 },
    { label: "Supervisors, furniture and fixtures manufacturing", value: 92022 },
    { label: "Supervisors, other mechanical and metal products manufacturing", value: 92023 },
    { label: "Supervisors, other products manufacturing and assembly", value: 92024 },
    { label: "Power engineers and power systems operators", value: 92100 },
    { label: "Water and waste treatment plant operators", value: 92101 },
    { label: "Administrative officers", value: 13100 },
    { label: "Property administrators", value: 13101 },
    { label: "Payroll administrators", value: 13102 },
    { label: "Administrative assistants", value: 13110 },
    { label: "Legal administrative assistants", value: 13111 },
    { label: "Medical administrative assistants", value: 13112 },
    { label: "Customs, ship and other brokers", value: 13200 },
    { label: "Production and transportation logistics coordinators", value: 13201 },
    { label: "Dental assistants and dental laboratory assistants", value: 33100 },
    { label: "Medical laboratory assistants and related technical occupations", value: 33101 },
    { label: "Nurse aides, orderlies and patient service associates", value: 33102 },
    { label: "Pharmacy technical assistants and pharmacy assistants", value: 33103 },
    { label: "Other assisting occupations in support of health services", value: 33109 },
    { label: "Elementary and secondary school teacher assistants", value: 43100 },
    { label: "Other instructors", value: 43109 },
    { label: "Sheriffs and bailiffs", value: 43200 },
    { label: "Correctional service officers", value: 43201 },
    { label: "By-law enforcement and other regulatory officers", value: 43202 },
    { label: "Border services, customs, and immigration officers", value: 43203 },
    { label: "Operations members of the Canadian Armed Forces", value: 43204 },
    { label: "Registrars, restorers, interpreters and other occupations related to museum and art galleries", value: 53100 },
    { label: "Photographers", value: 53110 },
    { label: "Motion pictures, broadcasting, photography and performing arts assistants and operators", value: 53111 },
    { label: "Dancers", value: 53120 },
    { label: "Actors, comedians and circus performers", value: 53121 },
    { label: "Painters, sculptors and other visual artists", value: 53122 },
    { label: "Theatre, fashion, exhibit and other creative designers", value: 53123 },
    { label: "Artisans and craftspersons", value: 53124 },
    { label: "Patternmakers - textile, leather and fur products", value: 53125 },
    { label: "Athletes", value: 53200 },
    { label: "Coaches", value: 53201 },
    { label: "Sports officials and referees", value: 53202 },
    { label: "Insurance agents and brokers", value: 63100 },
    { label: "Real estate agents and salespersons", value: 63101 },
    { label: "Financial sales representatives", value: 63102 },
    { label: "Cooks", value: 63200 },
    { label: "Butchers - retail and wholesale", value: 63201 },
    { label: "Bakers", value: 63202 },
    { label: "Hairstylists and barbers", value: 63210 },
    { label: "Estheticians, electrologists and related occupations", value: 63211 },
    { label: "Shoe repairers and shoemakers", value: 63220 },
    { label: "Upholsterers", value: 63221 },
    { label: "Concrete finishers", value: 73100 },
    { label: "Tilesetters", value: 73101 },
    { label: "Plasterers, drywall installers and finishers and lathers", value: 73102 },
    { label: "Roofers and shinglers", value: 73110 },
    { label: "Glaziers", value: 73111 },
    { label: "Painters and decorators (except interior decorators)", value: 73112 },
    { label: "Floor covering installers", value: 73113 },
    { label: "Residential and commercial installers and servicers", value: 73200 },
    { label: "General building maintenance workers and building superintendents", value: 73201 },
    { label: "Pest controllers and fumigators", value: 73202 },
    { label: "Other repairers and servicers", value: 73209 },
    { label: "Transport truck drivers", value: 73300 },
    { label: "Bus drivers, subway operators and other transit operators", value: 73301 },
    { label: "Railway and yard locomotive engineers", value: 73310 },
    { label: "Railway conductors and brakemen/women", value: 73311 },
    { label: "Heavy equipment operators", value: 73400 },
    { label: "Printing press operators", value: 73401 },
    { label: "Drillers and blasters - surface mining, quarrying and construction", value: 73402 },
    { label: "Underground production and development miners", value: 83100 },
    { label: "Oil and gas well drillers, servicers, testers and related workers", value: 83101 },
    { label: "Logging machinery operators", value: 83110 },
    { label: "Fishing masters and officers", value: 83120 },
    { label: "Fishermen/women", value: 83121 },
    { label: "Central control and process operators, mineral and metal processing", value: 93100 },
    { label: "Central control and process operators, petroleum, gas and chemical processing", value: 93101 },
    { label: "Pulping, papermaking and coating control operators", value: 93102 },
    { label: "Aircraft assemblers and aircraft assembly inspectors", value: 93200 },
    { label: "General office support workers", value: 14100 },
    { label: "Receptionists", value: 14101 },
    { label: "Personnel clerks", value: 14102 },
    { label: "Court clerks and related court services occupations", value: 14103 },
    { label: "Survey interviewers and statistical clerks", value: 14110 },
    { label: "Data entry clerks", value: 14111 },
    { label: "Desktop publishing operators and related occupations", value: 14112 },
    { label: "Accounting and related clerks", value: 14200 },
    { label: "Banking, insurance and other financial clerks", value: 14201 },
    { label: "Collection clerks", value: 14202 },
    { label: "Library assistants and clerks", value: 14300 },
    { label: "Correspondence, publication and regulatory clerks", value: 14301 },
    { label: "Shippers and receivers", value: 14400 },
    { label: "Storekeepers and partspersons", value: 14401 },
    { label: "Production logistics workers", value: 14402 },
    { label: "Purchasing and inventory control workers", value: 14403 },
    { label: "Dispatchers", value: 14404 },
    { label: "Transportation route and crew schedulers", value: 14405 },
    { label: "Home child care providers", value: 44100 },
    { label: "Home support workers, caregivers and related occupations", value: 44101 },
    { label: "Primary combat members of the Canadian Armed Forces", value: 44200 },
    { label: "Program leaders and instructors in recreation, sport and fitness", value: 54100 },
    { label: "Retail salespersons and visual merchandisers", value: 64100 },
    { label: "Sales and account representatives - wholesale trade (non-technical)", value: 64101 },
    { label: "Tailors, dressmakers, furriers and milliners", value: 64200 },
    { label: "Image, social and other personal consultants", value: 64201 },
    { label: "Ma\u00eetres d'h\u00f4tel and hosts/hostesses", value: 64300 },
    { label: "Bartenders", value: 64301 },
    { label: "Travel counsellors", value: 64310 },
    { label: "Pursers and flight attendants", value: 64311 },
    { label: "Airline ticket and service agents", value: 64312 },
    { label: "Ground and water transport ticket agents, cargo service representatives and related clerks", value: 64313 },
    { label: "Hotel front desk clerks", value: 64314 },
    { label: "Tour and travel guides", value: 64320 },
    { label: "Casino workers", value: 64321 },
    { label: "Outdoor sport and recreational guides", value: 64322 },
    { label: "Customer services representatives - financial institutions", value: 64400 },
    { label: "Postal services representatives", value: 64401 },
    { label: "Other customer and information services representatives", value: 64409 },
    { label: "Security guards and related security service occupations", value: 64410 },
    { label: "Mail and parcel sorters and related occupations", value: 74100 },
    { label: "Letter carriers", value: 74101 },
    { label: "Couriers and messengers", value: 74102 },
    { label: "Railway yard and track maintenance workers", value: 74200 },
    { label: "Water transport deck and engine room crew", value: 74201 },
    { label: "Air transport ramp attendants", value: 74202 },
    { label: "Automotive and heavy truck and equipment parts installers and servicers", value: 74203 },
    { label: "Utility maintenance workers", value: 74204 },
    { label: "Public works maintenance equipment operators and related workers", value: 74205 },
    { label: "Underground mine service and support workers", value: 84100 },
    { label: "Oil and gas well drilling and related workers and services operators", value: 84101 },
    { label: "Chain saw and skidder operators", value: 84110 },
    { label: "Silviculture and forestry workers", value: 84111 },
    { label: "Specialized livestock workers and farm machinery operators", value: 84120 },
    { label: "Fishing vessel deckhands", value: 84121 },
    { label: "Machine operators, mineral and metal processing", value: 94100 },
    { label: "Foundry workers", value: 94101 },
    { label: "Glass forming and finishing machine operators and glass cutters", value: 94102 },
    { label: "Concrete, clay and stone forming operators", value: 94103 },
    { label: "Inspectors and testers, mineral and metal processing", value: 94104 },
    { label: "Metalworking and forging machine operators", value: 94105 },
    { label: "Machining tool operators", value: 94106 },
    { label: "Machine operators of other metal products", value: 94107 },
    { label: "Chemical plant machine operators", value: 94110 },
    { label: "Plastics processing machine operators", value: 94111 },
    { label: "Rubber processing machine operators and related workers", value: 94112 },
    { label: "Sawmill machine operators", value: 94120 },
    { label: "Pulp mill, papermaking and finishing machine operators", value: 94121 },
    { label: "Paper converting machine operators", value: 94122 },
    { label: "Lumber graders and other wood processing inspectors and graders", value: 94123 },
    { label: "Woodworking machine operators", value: 94124 },
    { label: "Other wood processing machine operators", value: 94129 },
    { label: "Textile fibre and yarn, hide and pelt processing machine operators and workers", value: 94130 },
    { label: "Weavers, knitters and other fabric making occupations", value: 94131 },
    { label: "Industrial sewing machine operators", value: 94132 },
    { label: "Inspectors and graders, textile, fabric, fur and leather products manufacturing", value: 94133 },
    { label: "Process control and machine operators, food and beverage processing", value: 94140 },
    { label: "Industrial butchers and meat cutters, poultry preparers and related workers", value: 94141 },
    { label: "Fish and seafood plant workers", value: 94142 },
    { label: "Testers and graders, food and beverage processing", value: 94143 },
    { label: "Plateless printing equipment operators", value: 94150 },
    { label: "Camera, platemaking and other prepress occupations", value: 94151 },
    { label: "Binding and finishing machine operators", value: 94152 },
    { label: "Photographic and film processors", value: 94153 },
    { label: "Motor vehicle assemblers, inspectors and testers", value: 94200 },
    { label: "Electronics assemblers, fabricators, inspectors and testers", value: 94201 },
    { label: "Assemblers and inspectors, electrical appliance, apparatus and equipment manufacturing", value: 94202 },
    { label: "Assemblers, fabricators and inspectors, industrial electrical motors and transformers", value: 94203 },
    { label: "Mechanical assemblers and inspectors", value: 94204 },
    { label: "Machine operators and inspectors, electrical apparatus manufacturing", value: 94205 },
    { label: "Furniture and fixture assemblers, finishers, refinishers and inspectors", value: 94210 },
    { label: "Assemblers and inspectors of other wood products", value: 94211 },
    { label: "Plastic products assemblers, finishers and inspectors", value: 94212 },
    { label: "Industrial painters, coaters and metal finishing process operators", value: 94213 },
    { label: "Other products assemblers, finishers and inspectors", value: 94219 },
    { label: "Student monitors, crossing guards and related occupations", value: 45100 },
    { label: "Other performers", value: 55109 },
    { label: "Cashiers", value: 65100 },
    { label: "Service station attendants", value: 65101 },
    { label: "Store shelf stockers, clerks and order fillers", value: 65102 },
    { label: "Other sales related occupations", value: 65109 },
    { label: "Food and beverage servers", value: 65200 },
    { label: "Food counter attendants, kitchen helpers and related support occupations", value: 65201 },
    { label: "Meat cutters and fishmongers - retail and wholesale", value: 65202 },
    { label: "Support occupations in accommodation, travel and facilities set-up services", value: 65210 },
    { label: "Operators and attendants in amusement, recreation and sport", value: 65211 },
    { label: "Pet groomers and animal care workers", value: 65220 },
    { label: "Other support occupations in personal services", value: 65229 },
    { label: "Light duty cleaners", value: 65310 },
    { label: "Specialized cleaners", value: 65311 },
    { label: "Janitors, caretakers and heavy-duty cleaners", value: 65312 },
    { label: "Dry cleaning, laundry and related occupations", value: 65320 },
    { label: "Other service support occupations", value: 65329 },
    { label: "Longshore workers", value: 75100 },
    { label: "Material handlers", value: 75101 },
    { label: "Construction trades helpers and labourers", value: 75110 },
    { label: "Other trades helpers and labourers", value: 75119 },
    { label: "Taxi and limousine drivers and chauffeurs", value: 75200 },
    { label: "Delivery service drivers and door-to-door distributors", value: 75201 },
    { label: "Boat and cable ferry operators and related occupations", value: 75210 },
    { label: "Railway and motor transport labourers", value: 75211 },
    { label: "Public works and maintenance labourers", value: 75212 },
    { label: "Livestock labourers", value: 85100 },
    { label: "Harvesting labourers", value: 85101 },
    { label: "Aquaculture and marine harvest labourers", value: 85102 },
    { label: "Nursery and greenhouse labourers", value: 85103 },
    { label: "Trappers and hunters", value: 85104 },
    { label: "Mine labourers", value: 85110 },
    { label: "Oil and gas drilling, servicing and related labourers", value: 85111 },
    { label: "Logging and forestry labourers", value: 85120 },
    { label: "Landscaping and grounds maintenance labourers", value: 85121 },
    { label: "Labourers in mineral and metal processing", value: 95100 },
    { label: "Labourers in metal fabrication", value: 95101 },
    { label: "Labourers in chemical products processing and utilities", value: 95102 },
    { label: "Labourers in wood, pulp and paper processing", value: 95103 },
    { label: "Labourers in rubber and plastic products manufacturing", value: 95104 },
    { label: "Labourers in textile processing and cutting", value: 95105 },
    { label: "Labourers in food and beverage processing", value: 95106 },
    { label: "Labourers in fish and seafood processing", value: 95107 },
    { label: "Other labourers in processing, manufacturing and utilities", value: 95109 }
]