const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const morgan = require("morgan");
const rateLimit = require("express-rate-limit");
require("dotenv").config();

const app = express();
const PORT = process.env.LEADS_SERVICE_PORT || process.env.PORT || 3006;

// Security middleware
app.use(helmet());

// CORS configuration - Match UI_Reference API
const corsOptions = {
  origin: "*", // Allow all origins like the reference API
  credentials: false, // Set to false when origin is "*"
  methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
  allowedHeaders: [
    "Content-Type",
    "Authorization",
    "X-Request-ID",
    "auth-token", // Allow the custom auth-token header
    "accept",
    "origin",
    "x-requested-with",
  ],
  optionsSuccessStatus: 200, // Some legacy browsers choke on 204
};

app.use(cors(corsOptions));

// Rate limiting
const limiter = rateLimit({
  windowMs: parseInt(process.env.RATE_LIMIT_WINDOW_MS || "900000", 10),
  max: parseInt(process.env.RATE_LIMIT_MAX_REQUESTS || "100", 10),
  message: {
    success: false,
    error: {
      code: "RATE_LIMIT_EXCEEDED",
      message: "Too many requests, please try again later",
    },
  },
  standardHeaders: true,
  legacyHeaders: false,
});
app.use(limiter);

// Body parsing middleware
app.use(express.json({ limit: "10mb" }));
app.use(express.urlencoded({ extended: true, limit: "10mb" }));

// Logging middleware
app.use(morgan("combined"));

// Health check route
app.get("/health", (req, res) => {
  res.json({
    success: true,
    service: "leads-service",
    status: "healthy",
    timestamp: new Date().toISOString(),
    port: PORT,
  });
});

// CORS middleware handles OPTIONS requests automatically

// Leads API endpoints
app.get("/api/v1/lead/get-leads", (req, res) => {
  console.log("📋 Get leads request received:", req.query);

  const { pageNo, itemPerPage } = req.query;

  // Mock leads data matching the UI_Reference response format
  const leadsData = [
    {
      leads_uuid: "8ac7caad-69c9-4314-9222-00b4706814ae",
      referral_code: "NW-44",
      leads_code: "GBL250812180008939",
      terms_and_condition: 1,
      branch_name: "NOVA SCOTIA",
      branch_uuid: "91b78ebf-8ba7-45f8-baf4-051053aa8c47",
      service_type: "WORK_PERMIT",
      service_sub_type: null,
      applicant_first_name: "Jatin",
      applicant_last_name: "Kuamr",
      nationality: "India",
      country: "",
      state_or_province: "",
      country_of_residence: "Canada",
      status_in_country: "STUDY",
      unique_token_no: null,
      submitted_on: null,
      user_roles: null,
      current_residential_address: null,
      primary_language: null,
      english_exam_type: null,
      Date_of_IELTS_exam: null,
      overall_IELTS_score: null,
      which_intake_you_want_to_apply_for: null,
      intake_year: null,
      program_type_apply_for: null,
      highest_level_of_education: null,
      matriculation_start_date: null,
      matriculation_end_date: null,
      completion_year: null,
      school_name: null,
      percentage: null,
      math_marks: null,
      english_marks: null,
      senior_secondary_start_date: null,
      senior_secondary_end_date: null,
      senior_secondary_school_name: null,
      senior_secondary_completion_year: null,
      senior_secondary_field_of_study: null,
      senior_secondary_percentage: null,
      company_name: null,
      job_title: null,
      job_start_date: null,
      visa_refusal: null,
      valid_study_permit_visa: null,
      applicant_date_of_birth: "1997-08-11T00:00:00.000Z",
      age: 28,
      applicant_sex: "MALE",
      contact_number: "1234567890",
      email: "jatin@edgenroots.net",
      marital_status: "NEVER_MARRIED_OR_SINGLE",
      number_of_children: "",
      is_er_approved_outside_canada: null,
      education: [
        {
          to: "2024-08-25T18:30:00.000Z",
          from: "2022-08-25T18:30:00.000Z",
          country: "india",
          qualification: "MASTER_DEGREE_OR_PROFESSIONAL_DEGREE",
          is_eca_approved: 1,
          marks_percentage: "90",
          school_or_university: "lucknow university",
        },
        {
          to: "2024-08-25T18:30:00.000Z",
          from: "2020-08-25T18:30:00.000Z",
          country: "canada",
          qualification: "BECHELOR_DEGREE_OR_THREE_OR_MORE_YEAR_PROGRAM",
          is_eca_approved: 0,
          marks_percentage: "90",
          school_or_university: "test",
        },
      ],
      is_last_10_years: null,
      last_10_foreign_years: null,
      work_history: [
        {
          to: "2021-08",
          from: "2018-09",
          country: "canada",
          duration: 2,
          designation: "",
          company_name: "test",
          noc_job_code: "95105",
          noc_job_uuid: "76261817-1132-11f0-a003-0e525aef9233",
          location_type: "ON_SITE",
          noc_job_title: "Labourers in textile processing and cutting",
          adjustedDuration: 2,
          company_location: "abcd",
          employement_type: "FULL_TIME",
          work_description: null,
          currently_working: false,
        },
        {
          to: "2025-09",
          from: "2020-08",
          country: "canada",
          duration: 4,
          designation: "",
          company_name: "test",
          noc_job_code: "95107",
          noc_job_uuid: "762618f2-1132-11f0-a003-0e525aef9233",
          location_type: "ON_SITE",
          noc_job_title: "Labourers in fish and seafood processing",
          adjustedDuration: 4,
          company_location: "abcd ",
          employement_type: "FULL_TIME",
          work_description: null,
          currently_working: false,
        },
      ],
      english_language_test_type: "IELTS",
      english_test_result_less_than_two_years: "YES",
      english_ability_speaking: 10,
      english_ability_reading: 10,
      english_ability_writing: 10,
      english_ability_listening: 10,
      english_ability_total_points: 136,
      french_language_test_type: null,
      french_test_result_less_than_two_years: "NO",
      french_ability_speaking: null,
      french_ability_reading: null,
      french_ability_writing: null,
      french_ability_listening: null,
      second_language_ability_total_points: null,
      workAndeduc: null,
      wkrFrgExp: null,
      speakAndEdu: null,
      speakAndWork: null,
      sponsor_type: null,
      sponsor_income: null,
      currency_field: "",
      movable: null,
      immovable: null,
      net_worth: "0",
      travel_history: [
        {
          to_date: "",
          duration: "",
          from_date: "",
          description: "",
          destination: "Torronto Canada",
          purpose_of_travel: "",
        },
      ],
      upon_signing_of_this_agreement: null,
      upon_submission: null,
      upon_execution_of_this_agreement: null,
      HST: null,
      total_fees: null,
      spouse_first_name: "Test",
      spouse_last_name: "test",
      spouse_date_of_birth: "2000-10-15T07:00:00.000Z",
      spouse_sex: "FEMALE",
      spouse_has_degree_outside_canda_degree: null,
      spouse_education: [
        {
          to: "2024-08-19T18:30:00.000Z",
          from: "2020-08-19T18:30:00.000Z",
          country: "INDIA",
          qualification: "BECHELOR_DEGREE_OR_THREE_OR_MORE_YEAR_PROGRAM",
          marks_percentage: "80",
          school_or_university:
            "I.K. Gujral Punjab Technical University Jalandhar",
        },
      ],
      spouse_education_points: null,
      is_spouse_last_10_years: null,
      spouse_work_history: [],
      spouse_work_points: null,
      spouse_english_language_test_type: null,
      spouse_english_test_result_less_than_two_years: "NO",
      spouse_english_ability_speaking: null,
      spouse_english_ability_reading: null,
      spouse_english_ability_writing: null,
      spouse_english_ability_listening: null,
      spouse_english_ability_total_points: 0,
      spouse_french_language_test_type: null,
      spouse_french_test_result_less_than_two_years: null,
      spouse_french_ability_speaking: null,
      spouse_french_ability_reading: null,
      spouse_french_ability_writing: null,
      spouse_french_ability_listening: null,
      self_employment: null,
      relatives_in_canada: "YES",
      is_valid_job_offer: "NO",
      noc_teer_job_offer_type: null,
      province_or_territory_nomination: "NO",
      certificate_of_qualification: "NO",
      certificate_points: null,
      applicant_crs_points: {
        total: 511,
        spouse_factor: {
          subtotal: 0,
          level_of_education: 0,
          first_official_language: 0,
          canadian_work_experience: 0,
        },
        additional_point: {
          subtotal: 30,
          job_offer: 0,
          study_in_canada: 30,
          sibling_in_canada: 0,
          french_language_skills: 0,
          provinicial_nomination: 0,
        },
        core_human_capital_factor: {
          age: 110,
          subtotal: 461,
          level_of_education: 135,
          official_languages: {
            first_official_language: 136,
            second_official_language: 0,
          },
          canadian_work_experience: 80,
          official_languages_subtotal: 136,
        },
        skill_transferbility_factor: {
          subtotal: 50,
          education: {
            subtotal: 50,
            canadian_work_experience_and_education: 50,
            official_language_proficiencey_and_education: 50,
          },
          foreign_work_experience: {
            subtotal: 0,
            canadian_and_foreign_work_experience: 0,
            official_language_proficiencey_and_foreign_work_experience: 0,
          },
          certificate_of_qualification: 0,
        },
        comprehensive_ranking_system_formula_grand_total: 541,
      },
      total_additional: null,
      additional_points: null,
      additionalPoints: null,
      leads_source: "OTHER",
      total: 511,
      passport: null,
      wes_document: null,
      iltes_document: null,
      resume: null,
      funds_available: "25001-50000",
      prior_travel_history: "YES",
      country_code: "+1",
      childrens_details: [
        {
          age: 26,
          last_name: "Usered",
          first_name: "Tested",
          date_of_birth: "1999-08-19T18:30:00.000Z",
        },
      ],
      no_work_experience: 0,
      relative_relation: "MOTHER",
      spouse_no_work_experience: 0,
      asignee_uuid: "b0c3fe31-5b09-419c-a180-1b1906ab4b6e",
      asignee_email: "kamal@edgenroots.net",
      asignee_name: "Kamal Admin",
      applicant_oinp_points: {
        oinp_total: 44,
        job_offer_points: {
          wage: 8,
          location: 0,
          job_tenure: 3,
          noc_category: 10,
          oinp_subtotal: 44,
          teer_category: 10,
          earnings_history: 3,
          work_permit_status: 10,
        },
      },
      job_offer: [
        {
          wage: "35_TO_39.99",
          location: "TORONTO",
          job_tenure: "6_MONTH_OR_MORE",
          noc_category: "0,2,3",
          teer_category: "0_OR_1",
          earnings_history: "40_OR_MORE",
          work_permit_status: "WITH_VALID",
        },
      ],
      oinp_subtotal: null,
      oinp_total: null,
      specify: "Person",
      notes: null,
      questionnaire_name: null,
      questionnaire_uuid: null,
      comment: null,
      asignee: [
        {
          asignee_name: "Kamal Employee",
          asignee_email: "web.kamaldeep@gmail.com",
          asignee_uuid: "f354f194-5a17-4471-a7a9-de2a34868746",
          created_by_uuid: "6c96e128-3b41-4a8e-86a6-e937323e84ed",
          branch_uuid: "91b78ebf-8ba7-45f8-baf4-051053aa8c47",
          user_uuid: "f354f194-5a17-4471-a7a9-de2a34868746",
        },
      ],
      time_to_contact: "9:00 am to 12:00pm",
      assigned_to_id: "44",
      status: "ACTIVE",
      created_by_uuid: null,
      created_by_name: "",
      modified_by_uuid: "0522b6ac-3ec7-4a6f-92b0-f6becd6e346f",
      modified_by_name: "Umesh Yadav",
      create_ts: "2025-08-12T18:00:09.000Z",
      insert_ts: "2025-09-09T17:22:18.000Z",
    },
    {
      leads_uuid: "26dae147-56b4-4e00-abe0-7e1220a305aa",
      referral_code: null,
      leads_code: "GBL250905082807721",
      terms_and_condition: null,
      branch_name: "NOVA SCOTIA",
      branch_uuid: "91b786bf-49f8-b8a7-ba14-051053aa8c47",
      service_type: "PR",
      service_sub_type: "Permanent Residence",
      applicant_first_name: "Akshay",
      applicant_last_name: "Dubey",
      nationality: "India",
      country: "Canada",
      state_or_province: "Nova Scotia",
      country_of_residence: null,
      status_in_country: null,
      unique_token_no: null,
      submitted_on: null,
      user_roles: null,
      current_residential_address: null,
      primary_language: null,
      english_exam_type: null,
      Date_of_IELTS_exam: null,
      overall_IELTS_score: null,
      which_intake_you_want_to_apply_for: null,
      intake_year: null,
      program_type_apply_for: null,
      highest_level_of_education: null,
      matriculation_start_date: null,
      matriculation_end_date: null,
      completion_year: null,
      school_name: null,
      percentage: null,
      math_marks: null,
      english_marks: null,
      senior_secondary_start_date: null,
      senior_secondary_end_date: null,
      senior_secondary_school_name: null,
      senior_secondary_completion_year: null,
      senior_secondary_field_of_study: null,
      senior_secondary_percentage: null,
      company_name: null,
      job_title: null,
      job_start_date: null,
      visa_refusal: null,
      valid_study_permit_visa: null,
      applicant_date_of_birth: "1989-07-29T00:00:00.000Z",
      age: null,
      applicant_sex: null,
      contact_number: "1234567890",
      email: "akshay@gmail.com",
      marital_status: "MARRIED",
      number_of_children: null,
      is_er_approved_outside_canada: null,
      education: [],
      is_last_10_years: null,
      last_10_foreign_years: null,
      work_history: [],
      english_language_test_type: null,
      english_test_result_less_than_two_years: null,
      english_ability_speaking: null,
      english_ability_reading: null,
      english_ability_writing: null,
      english_ability_listening: null,
      english_ability_total_points: null,
      french_language_test_type: null,
      french_test_result_less_than_two_years: null,
      french_ability_speaking: null,
      french_ability_reading: null,
      french_ability_writing: null,
      french_ability_listening: null,
      second_language_ability_total_points: null,
      workAndeduc: null,
      wkrFrgExp: null,
      speakAndEdu: null,
      speakAndWork: null,
      sponsor_type: null,
      sponsor_income: null,
      currency_field: null,
      movable: null,
      immovable: null,
      net_worth: null,
      travel_history: [],
      upon_signing_of_this_agreement: null,
      upon_submission: null,
      upon_execution_of_this_agreement: null,
      HST: null,
      total_fees: null,
      spouse_first_name: null,
      spouse_last_name: null,
      spouse_date_of_birth: null,
      spouse_sex: null,
      spouse_has_degree_outside_canda_degree: null,
      spouse_education: [],
      spouse_education_points: null,
      is_spouse_last_10_years: null,
      spouse_work_history: [],
      spouse_work_points: null,
      spouse_english_language_test_type: null,
      spouse_english_test_result_less_than_two_years: null,
      spouse_english_ability_speaking: null,
      spouse_english_ability_reading: null,
      spouse_english_ability_writing: null,
      spouse_english_ability_listening: null,
      spouse_english_ability_total_points: null,
      spouse_french_language_test_type: null,
      spouse_french_test_result_less_than_two_years: null,
      spouse_french_ability_speaking: null,
      spouse_french_ability_reading: null,
      spouse_french_ability_writing: null,
      spouse_french_ability_listening: null,
      self_employment: null,
      relatives_in_canada: null,
      is_valid_job_offer: null,
      noc_teer_job_offer_type: null,
      province_or_territory_nomination: null,
      certificate_of_qualification: null,
      certificate_points: null,
      applicant_crs_points: null,
      total_additional: null,
      additional_points: null,
      additionalPoints: null,
      leads_source: null,
      total: null,
      passport: null,
      wes_document: null,
      iltes_document: null,
      resume: null,
      funds_available: null,
      prior_travel_history: null,
      country_code: null,
      childrens_details: null,
      no_work_experience: null,
      relative_relation: null,
      spouse_no_work_experience: null,
      asignee_uuid: null,
      asignee_email: null,
      asignee_name: null,
      applicant_oinp_points: null,
      job_offer: null,
      oinp_subtotal: null,
      oinp_total: null,
      specify: null,
      notes: null,
      questionnaire_name: null,
      questionnaire_uuid: null,
      comment: null,
      asignee: [],
      time_to_contact: null,
      assigned_to_id: null,
      status: "ACTIVE",
      created_by_uuid: null,
      created_by_name: "Ramesh",
      modified_by_uuid: null,
      modified_by_name: null,
      create_ts: "2025-09-05T08:28:07.000Z",
      insert_ts: "2025-09-05T08:28:48.000Z",
    },
    {
      leads_uuid: "0e0c367d-078a-4651-b1a1-e71b8384dd73",
      referral_code: "UME2556",
      leads_code: "GBL250812160806684",
      terms_and_condition: 1,
      branch_name: "NOVA SCOTIA",
      branch_uuid: "91b78ebf-8ba7-45f8-baf4-051053aa8c47",
      service_type: "",
      service_sub_type: null,
      applicant_first_name: "Umesh",
      applicant_last_name: "Yadav",
      nationality: "India",
      country: "",
      state_or_province: "",
      country_of_residence: "Canada",
      status_in_country: "STUDY",
      unique_token_no: null,
      submitted_on: null,
      user_roles: null,
      current_residential_address: null,
      primary_language: null,
      english_exam_type: null,
      Date_of_IELTS_exam: null,
      overall_IELTS_score: null,
      which_intake_you_want_to_apply_for: null,
      intake_year: null,
      program_type_apply_for: null,
      highest_level_of_education: null,
      matriculation_start_date: null,
      matriculation_end_date: null,
      completion_year: null,
      school_name: null,
      percentage: null,
      math_marks: null,
      english_marks: null,
      senior_secondary_start_date: null,
      senior_secondary_end_date: null,
      senior_secondary_school_name: null,
      senior_secondary_completion_year: null,
      senior_secondary_field_of_study: null,
      senior_secondary_percentage: null,
      company_name: null,
      job_title: null,
      job_start_date: null,
      visa_refusal: null,
      valid_study_permit_visa: null,
      applicant_date_of_birth: "1997-08-11T00:00:00.000Z",
      age: 28,
      applicant_sex: "MALE",
      contact_number: "1234567890",
      email: "umesh@edgenroots.net",
      marital_status: "MARRIED",
      number_of_children: "",
      is_er_approved_outside_canada: null,
      education: [
        {
          to: "2019-05-30T18:30:00.000Z",
          from: "2015-07-31T18:30:00.000Z",
          country: "INDIA",
          qualification: "BECHELOR_DEGREE_OR_THREE_OR_MORE_YEAR_PROGRAM",
          marks_percentage: "80",
          school_or_university:
            "I.K. Gujral Punjab Technical University Jalandhar",
        },
      ],
      is_last_10_years: null,
      last_10_foreign_years: null,
      work_history: [],
      english_language_test_type: "IELTS",
      english_test_result_less_than_two_years: "YES",
      english_ability_speaking: 10,
      english_ability_reading: 10,
      english_ability_writing: 10,
      english_ability_listening: 10,
      english_ability_total_points: 128,
      french_language_test_type: "TEF",
      french_test_result_less_than_two_years: "YES",
      french_ability_speaking: 10,
      french_ability_reading: 10,
      french_ability_writing: 10,
      french_ability_listening: 10,
      second_language_ability_total_points: null,
      workAndeduc: null,
      wkrFrgExp: null,
      speakAndEdu: null,
      speakAndWork: null,
      sponsor_type: null,
      sponsor_income: null,
      currency_field: "",
      movable: null,
      immovable: null,
      net_worth: "0",
      travel_history: [],
      upon_signing_of_this_agreement: null,
      upon_submission: null,
      upon_execution_of_this_agreement: null,
      HST: null,
      total_fees: null,
      spouse_first_name: "Test",
      spouse_last_name: "Name",
      spouse_date_of_birth: "1998-08-11T18:30:00.000Z",
      spouse_sex: "FEMALE",
      spouse_has_degree_outside_canda_degree: null,
      spouse_education: [],
      spouse_education_points: null,
      is_spouse_last_10_years: null,
      spouse_work_history: [],
      spouse_work_points: null,
      spouse_english_language_test_type: null,
      spouse_english_test_result_less_than_two_years: "NO",
      spouse_english_ability_speaking: null,
      spouse_english_ability_reading: null,
      spouse_english_ability_writing: null,
      spouse_english_ability_listening: null,
      spouse_english_ability_total_points: 0,
      spouse_french_language_test_type: null,
      spouse_french_test_result_less_than_two_years: null,
      spouse_french_ability_speaking: null,
      spouse_french_ability_reading: null,
      spouse_french_ability_writing: null,
      spouse_french_ability_listening: null,
      self_employment: null,
      relatives_in_canada: "NO",
      is_valid_job_offer: "NO",
      noc_teer_job_offer_type: null,
      province_or_territory_nomination: "NO",
      certificate_of_qualification: "NO",
      certificate_points: null,
      applicant_crs_points: {
        total: 387,
        spouse_factor: {
          subtotal: 0,
          level_of_education: 0,
          first_official_language: 0,
          canadian_work_experience: 0,
        },
        additional_point: {
          subtotal: 50,
          job_offer: 0,
          study_in_canada: 0,
          sibling_in_canada: 0,
          french_language_skills: 50,
          provinicial_nomination: 0,
        },
        core_human_capital_factor: {
          age: 100,
          subtotal: 362,
          level_of_education: 112,
          official_languages: {
            first_official_language: 128,
            second_official_language: 22,
          },
          canadian_work_experience: 0,
          official_languages_subtotal: 150,
        },
        skill_transferbility_factor: {
          subtotal: 25,
          education: {
            subtotal: 25,
            canadian_work_experience_and_education: 0,
            official_language_proficiencey_and_education: 25,
          },
          foreign_work_experience: {
            subtotal: 0,
            canadian_and_foreign_work_experience: 0,
            official_language_proficiencey_and_foreign_work_experience: 0,
          },
          certificate_of_qualification: 0,
        },
        comprehensive_ranking_system_formula_grand_total: 437,
      },
      total_additional: null,
      additional_points: null,
      additionalPoints: null,
      leads_source: "GOOGLE",
      total: 387,
      passport: null,
      wes_document: null,
      iltes_document: null,
      resume: null,
      funds_available: "25001-50000",
      prior_travel_history: "NO",
      country_code: "+1",
      childrens_details: [],
      no_work_experience: 1,
      relative_relation: null,
      spouse_no_work_experience: 1,
      asignee_uuid: null,
      asignee_email: null,
      asignee_name: null,
      applicant_oinp_points: null,
      job_offer: null,
      oinp_subtotal: null,
      oinp_total: null,
      specify: null,
      notes: null,
      questionnaire_name: null,
      questionnaire_uuid: null,
      comment: null,
      asignee: [
        {
          asignee_name: "Kamal Employee",
          asignee_email: "web.kamaldeep@gmail.com",
          asignee_uuid: "f354f194-5a17-4471-a7a9-de2a34868746",
          created_by_uuid: "6c96e128-3b41-4a8e-86a6-e937323e84ed",
          branch_uuid: "91b78ebf-8ba7-45f8-baf4-051053aa8c47",
          user_uuid: "f354f194-5a17-4471-a7a9-de2a34868746",
        },
      ],
      time_to_contact: null,
      assigned_to_id: "44",
      status: "ACTIVE",
      created_by_uuid: "b0c3fe31-5b09-419c-a180-1b1906ab4b6e",
      created_by_name: "Kamal Admin",
      modified_by_uuid: "0522b6ac-3ec7-4a6f-92b0-f6becd6e346f",
      modified_by_name: "Umesh Yadav",
      create_ts: "2025-08-12T16:08:06.000Z",
      insert_ts: "2025-08-26T15:18:20.000Z",
    },
  ];

  res.json({
    message: "All leads",
    currentRecords: parseInt(itemPerPage) || 3,
    data: leadsData.slice(0, parseInt(itemPerPage) || 3),
  });
});

// 404 handler
app.use("*", (req, res) => {
  res.status(404).json({
    success: false,
    error: {
      code: "NOT_FOUND",
      message: "Route not found",
    },
    timestamp: new Date().toISOString(),
  });
});

// Start server
app.listen(PORT, () => {
  console.log(`📋 Leads service running on port ${PORT}`);
  console.log(`📊 Health check: http://localhost:${PORT}/health`);
  console.log(`📋 Leads API: http://localhost:${PORT}/api/v1/lead/get-leads`);
});
